package onlinemarket.model;
// default package
// Generated Jan 2, 2018 4:57:38 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import onlinemarket.model.other.AdvancedValidation;
import onlinemarket.validation.UniqueBrandSlug;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "tb_brand", schema = "dbo", catalog = "SmartMarket")
@UniqueBrandSlug(groups = {AdvancedValidation.CheckSlug.class})
public class Brand implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String slug;
	private String beforeSlug;
	private String imagePath;
	private String description;
	private Date createDate;
	private Date updateDate;
	private Set<Product> products = new HashSet<Product>(0);
	private Set<Event> events = new HashSet<Event>(0);

	public Brand() {
	}

	public Brand(String name, String slug, Date createDate) {
		this.name = name;
		this.slug = slug;
		this.createDate = createDate;
	}

	public Brand(String name, String slug, String imagePath, String description, Date createDate,
			Date updateDate, Set<Product> products, Set<Event> events) {
		this.name = name;
		this.slug = slug;
		this.imagePath = imagePath;
		this.description = description;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.products = products;
		this.events = events;
	}

    public Brand(Integer id) {
    }

    @Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "_id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	@NotEmpty
	@Size(min = 2, max = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slug", nullable = false, length = 64, unique = true)
	@NotEmpty
	@Size(min = 2, max = 64)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}


	@Transient
	public String getBeforeSlug() {
		return beforeSlug;
	}

	public void setBeforeSlug(String beforeSlug) {
		this.beforeSlug = beforeSlug;
	}
	
	@Column(name = "image_path")
	@Size(max = 2048)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Column(name = "description")
	@Size(max = 1000, min = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 23)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tb_event_brand", schema = "dbo", catalog = "SmartMarket", joinColumns = {
			@JoinColumn(name = "brand_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "event_id", nullable = false, updatable = false) })
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((slug == null) ? 0 : slug.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Brand other = (Brand) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (slug == null) {
			if (other.slug != null)
				return false;
		} else if (!slug.equals(other.slug))
			return false;
		return true;
	}

}
