package onlinemarket.model;
// default package
// Generated Jan 2, 2018 4:57:38 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "tb_order", schema = "dbo", catalog = "SmartMarket")
public class Order implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private User user;
	private Long totalPaid;
	private Long totalPaidReal;
	private Integer totalProduct;
	private Integer totalShipping;
	private Byte status;
	private Date invoiceDate;
	private Date createDate;
	private Date updateDate;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);
	private Set<Event> events = new HashSet<Event>(0);
	private Set<Address> adresses = new HashSet<Address>(0);

	public Order() {
	}

	public Order(User user) {
		this.user = user;
	}

	public Order(User user, Long totalPaid, Long totalPaidReal, Integer totalProduct, Integer totalShipping,
			Byte status, Date invoiceDate, Date createDate, Date updateDate, Set<OrderDetail> orderDetails,
			Set<Event> events, Set<Address> adresses) {
		this.user = user;
		this.totalPaid = totalPaid;
		this.totalPaidReal = totalPaidReal;
		this.totalProduct = totalProduct;
		this.totalShipping = totalShipping;
		this.status = status;
		this.invoiceDate = invoiceDate;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.orderDetails = orderDetails;
		this.events = events;
		this.adresses = adresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "_id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "total_paid", precision = 13, scale = 0)
	public Long getTotalPaid() {
		return this.totalPaid;
	}

	public void setTotalPaid(Long totalPaid) {
		this.totalPaid = totalPaid;
	}

	@Column(name = "total_paid_real", precision = 13, scale = 0)
	public Long getTotalPaidReal() {
		return this.totalPaidReal;
	}

	public void setTotalPaidReal(Long totalPaidReal) {
		this.totalPaidReal = totalPaidReal;
	}

	@Column(name = "total_product")
	public Integer getTotalProduct() {
		return this.totalProduct;
	}

	public void setTotalProduct(Integer totalProduct) {
		this.totalProduct = totalProduct;
	}

	@Column(name = "total_shipping")
	public Integer getTotalShipping() {
		return this.totalShipping;
	}

	public void setTotalShipping(Integer totalShipping) {
		this.totalShipping = totalShipping;
	}

	@Column(name = "[status]")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "invoice_date", length = 23)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 23)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tb_event_order", schema = "dbo", catalog = "SmartMarket", joinColumns = {
			@JoinColumn(name = "order_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "event_id", nullable = false, updatable = false) })
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tb_address_order", schema = "dbo", catalog = "SmartMarket", joinColumns = {
			@JoinColumn(name = "id_order", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_address", nullable = false, updatable = false) })
	public Set<Address> getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Set<Address> adresses) {
		this.adresses = adresses;
	}

}
