package onlinemarket.model;
// default package
// Generated Jan 2, 2018 4:57:38 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductAttributeId generated by hbm2java
 */
@Embeddable
public class ProductAttributeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int attributeId;
	private int productId;

	public ProductAttributeId() {
	}

	public ProductAttributeId(int attributeId, int productId) {
		this.attributeId = attributeId;
		this.productId = productId;
	}

	@Column(name = "attribute_id", nullable = false)
	public int getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(int attributeId) {
		this.attributeId = attributeId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductAttributeId))
			return false;
		ProductAttributeId castOther = (ProductAttributeId) other;

		return (this.getAttributeId() == castOther.getAttributeId())
				&& (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAttributeId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
