package onlinemarket.model;
// default package
// Generated Jan 2, 2018 4:57:38 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Range;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "tb_province", schema = "dbo", catalog = "SmartMarket")
public class Province implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Byte id;
	private String name;
	private long shippingFee;
	private Set<Address> addresses = new HashSet<Address>(0);

	public Province() {
	}

	public Province(String name, long shippingFee) {
		this.name = name;
		this.shippingFee = shippingFee;
	}

	public Province(String name, long shippingFee, Set<Address> addresses) {
		this.name = name;
		this.shippingFee = shippingFee;
		this.addresses = addresses;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "_id", unique = true, nullable = false)
	public Byte getId() {
		return this.id;
	}

	public void setId(Byte id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "shipping_fee", nullable = false, precision = 13, scale = 0)
	@Range(max=1000000000, min = 0)
	public long getShippingFee() {
		return this.shippingFee;
	}

	public void setShippingFee(long shippingFee) {
		this.shippingFee = shippingFee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "province")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
