package onlinemarket.model;
// default package
// Generated Jan 2, 2018 4:57:38 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * RatingStatistic generated by hbm2java
 */
@Entity
@Table(name = "tb_statistic_rating", schema = "dbo", catalog = "SmartMarket")
public class RatingStatistic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Product product;
	private double averageScore;
	private int totalScore;
	private int userCount;

	public RatingStatistic() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "average_score", nullable = false, precision = 53, scale = 0)
	public double getAverageScore() {
		return this.averageScore;
	}

	public void setAverageScore(double averageScore) {
		this.averageScore = averageScore;
	}

	@Column(name = "total_score", nullable = false)
	public int getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(int totalScore) {
		this.totalScore = totalScore;
	}

	@Column(name = "user_count", nullable = false)
	public int getUserCount() {
		return this.userCount;
	}

	public void setUserCount(int userCount) {
		this.userCount = userCount;
	}

}
